export const data = [
  {
    id: "ihhBca5xs",
    name: "임의진",
    position: "선생님",
    gymName: "시청 피트니스온",
    gymAddress: "서울 중구 무교동",
    profileImage:
      "https://api.da-gym.net/trainers/images/ihhBca5xs+2Nq4kXKZBZem8rjkCAdKT.jpg",
    exerciseTypes: ["P.T"],
    isFreeTrial: false,
    isOnetimeLesson: false,
    paymentAvailable: true,
    rate: 0,
    reviewCount: 0,
  },
  {
    id: "23nBfgiuo7",
    name: "정치운",
    position: "선생님",
    gymName: "시청 피트니스온",
    gymAddress: "서울 중구 무교동",
    profileImage:
      "https://api.da-gym.net/trainers/images/23nBfgiuo7+2QSoJqqiFcup3qdgM6nx3.jpg",
    exerciseTypes: ["P.T"],
    isFreeTrial: false,
    isOnetimeLesson: false,
    paymentAvailable: true,
    rate: 0,
    reviewCount: 0,
  },
  {
    id: "zWTWVDuCp",
    name: "김옥철",
    position: "선생님",
    gymName: "시청 피트니스온",
    gymAddress: "서울 중구 무교동",
    profileImage:
      "https://api.da-gym.net/trainers/images/zWTWVDuCp+2S6kYxXuYWYcpfcdCqJns.jpg",
    exerciseTypes: ["P.T"],
    isFreeTrial: false,
    isOnetimeLesson: true,
    paymentAvailable: true,
    rate: 0,
    reviewCount: 0,
  },
  {
    id: "29PrhKP773",
    name: "이준명",
    position: "선생님",
    gymName: "시청 피트니스온",
    gymAddress: "서울 중구 무교동",
    profileImage:
      "https://api.da-gym.net/trainers/images/29PrhKP773+2S62ezfiVtZxCDPku9zrw.jpg",
    exerciseTypes: ["P.T"],
    isFreeTrial: false,
    isOnetimeLesson: true,
    paymentAvailable: true,
    rate: 0,
    reviewCount: 0,
  },
  {
    id: "5rdCbfFKH3",
    name: "하승준",
    position: "선생님",
    gymName: "회현 더코어필라테스",
    gymAddress: "서울 중구 회현동1가",
    profileImage:
      "https://api.da-gym.net/trainers/images/5rdCbfFKH3+KXFUT19xf4eB1DHLEmZ.jpg",
    exerciseTypes: ["P.T"],
    isFreeTrial: false,
    isOnetimeLesson: false,
    paymentAvailable: true,
    rate: 0,
    reviewCount: 0,
  },
  {
    id: "2UAv7euiLG",
    name: "이태훈",
    position: "선생님",
    gymName: "광화문 MCT GYM",
    gymAddress: "서울 종로구 내수동",
    profileImage:
      "https://api.da-gym.net/trainers/images/2UAv7euiLG+FVLypwK3KG57.jpg",
    exerciseTypes: ["P.T"],
    isFreeTrial: false,
    isOnetimeLesson: false,
    paymentAvailable: true,
    rate: 0,
    reviewCount: 0,
  },
  {
    id: "uMB5JJ9yQ",
    name: "이경주",
    position: "선생님",
    gymName: "광화문 MCT GYM",
    gymAddress: "서울 종로구 내수동",
    profileImage:
      "https://api.da-gym.net/trainers/images/uMB5JJ9yQ+HfTkFSuC2Ptk.jpg",
    exerciseTypes: ["P.T"],
    isFreeTrial: false,
    isOnetimeLesson: true,
    paymentAvailable: true,
    rate: 0,
    reviewCount: 0,
  },
  {
    id: "isefKqeRD",
    name: "김한수",
    position: "선생님",
    gymName: "광화문 MCT GYM",
    gymAddress: "서울 종로구 내수동",
    profileImage:
      "https://api.da-gym.net/trainers/images/isefKqeRD+5Ha215VskJ.jpg",
    exerciseTypes: ["P.T"],
    isFreeTrial: false,
    isOnetimeLesson: true,
    paymentAvailable: true,
    rate: 0,
    reviewCount: 0,
  },
  {
    id: "rfoosx7HU",
    name: "나해찬",
    position: "선생님",
    gymName: "광화문 MCT GYM",
    gymAddress: "서울 종로구 내수동",
    profileImage:
      "https://api.da-gym.net/trainers/images/rfoosx7HU+TBbZzwQevD7t.jpg",
    exerciseTypes: ["P.T"],
    isFreeTrial: false,
    isOnetimeLesson: false,
    paymentAvailable: true,
    rate: 0,
    reviewCount: 0,
  },
  {
    id: "vwJJMLhnE",
    name: "박용덕",
    position: "선생님",
    gymName: "서대문 짐피닉스 PT스튜디오",
    gymAddress: "서울 종로구 교남동",
    profileImage:
      "https://api.da-gym.net/trainers/images/vwJJMLhnE+ei5kTZsEybe.jpg",
    exerciseTypes: ["P.T"],
    isFreeTrial: false,
    isOnetimeLesson: false,
    paymentAvailable: true,
    rate: 0,
    reviewCount: 0,
  },
  {
    id: "28tUTBVRsY",
    name: "윤대희",
    position: "선생님",
    gymName: "서대문역 VIP 휘트니스",
    gymAddress: "서울 서대문구 충정로2가",
    profileImage:
      "https://api.da-gym.net/trainers/images/28tUTBVRsY+GXZRuKC4zqcj.jpg",
    exerciseTypes: ["P.T"],
    isFreeTrial: false,
    isOnetimeLesson: false,
    paymentAvailable: true,
    rate: 0,
    reviewCount: 0,
  },
  {
    id: "28zSzopA3y",
    name: "박경진",
    position: "선생님",
    gymName: "아현 247휘트니스&필라테스",
    gymAddress: "서울 서대문구 북아현동",
    profileImage:
      "https://api.da-gym.net/trainers/images/28zSzopA3y+ExuLVzkQ32d3.jpg",
    exerciseTypes: ["P.T"],
    isFreeTrial: false,
    isOnetimeLesson: false,
    paymentAvailable: true,
    rate: 5,
    reviewCount: 1,
  },
  {
    id: "hWyLQbRd1",
    name: "유재훈",
    position: "선생님",
    gymName: "아현 247휘트니스&필라테스",
    gymAddress: "서울 서대문구 북아현동",
    profileImage:
      "https://api.da-gym.net/trainers/images/hWyLQbRd1+eabvUtyswUbZcWmsZro.jpg",
    exerciseTypes: ["P.T"],
    isFreeTrial: false,
    isOnetimeLesson: true,
    paymentAvailable: true,
    rate: 0,
    reviewCount: 0,
  },
  {
    id: "qDensYY5s",
    name: "백수민",
    position: "선생님",
    gymName: "아현 247휘트니스&필라테스",
    gymAddress: "서울 서대문구 북아현동",
    profileImage:
      "https://api.da-gym.net/trainers/images/qDensYY5s+2P9SUQjeve716w7xemsru.jpg",
    exerciseTypes: ["P.T"],
    isFreeTrial: false,
    isOnetimeLesson: false,
    paymentAvailable: true,
    rate: 0,
    reviewCount: 0,
  },
  {
    id: "Abv9ft6Wwt",
    name: "배진우",
    position: "선생님",
    gymName: "아현 247휘트니스&필라테스",
    gymAddress: "서울 서대문구 북아현동",
    profileImage:
      "https://api.da-gym.net/trainers/images/Abv9ft6Wwt+2Nrts9B5k3zDvhpoyen6c.jpg",
    exerciseTypes: ["P.T"],
    isFreeTrial: false,
    isOnetimeLesson: false,
    paymentAvailable: true,
    rate: 0,
    reviewCount: 0,
  },
  {
    id: "6ZhWgBPUxs",
    name: "음지영",
    position: "선생님",
    gymName: "아현 247휘트니스&필라테스",
    gymAddress: "서울 서대문구 북아현동",
    profileImage:
      "https://api.da-gym.net/trainers/images/6ZhWgBPUxs+2YYzz3xNoUvBVY7tQXHAS.jpg",
    exerciseTypes: ["P.T"],
    isFreeTrial: false,
    isOnetimeLesson: false,
    paymentAvailable: true,
    rate: 0,
    reviewCount: 0,
  },
  {
    id: "86zLs2wjZh",
    name: "이창근",
    position: "선생님",
    gymName: "애오개 헬스존",
    gymAddress: "서울 마포구 공덕동",
    profileImage:
      "https://api.da-gym.net/trainers/images/86zLs2wjZh+VdGWQSTGoHTh.jpg",
    exerciseTypes: ["P.T"],
    isFreeTrial: false,
    isOnetimeLesson: false,
    paymentAvailable: true,
    rate: 5,
    reviewCount: 1,
  },
  {
    id: "4P3PzQTsoP",
    name: "편수진",
    position: "선생님",
    gymName: "애오개 헬스존",
    gymAddress: "서울 마포구 공덕동",
    profileImage:
      "https://api.da-gym.net/trainers/images/4P3PzQTsoP+inYto1HiikG.jpg",
    exerciseTypes: ["P.T"],
    isFreeTrial: false,
    isOnetimeLesson: true,
    paymentAvailable: true,
    rate: 5,
    reviewCount: 1,
  },
  {
    id: "281BaMRRMN",
    name: "곽나은",
    position: "선생님",
    gymName: "애오개 헬스존",
    gymAddress: "서울 마포구 공덕동",
    profileImage:
      "https://api.da-gym.net/trainers/images/281BaMRRMN+Q4xCv2h4aexr.jpg",
    exerciseTypes: ["P.T"],
    isFreeTrial: false,
    isOnetimeLesson: true,
    paymentAvailable: true,
    rate: 0,
    reviewCount: 0,
  },
  {
    id: "2KDXyGZGWa",
    name: "최윤선",
    position: "선생님",
    gymName: "숙대입구 망고짐",
    gymAddress: "서울 용산구 남영동",
    profileImage:
      "https://api.da-gym.net/trainers/images/2KDXyGZGWa+KTAn1amaM9C6CbUZ4yQ.jpg",
    exerciseTypes: ["P.T"],
    isFreeTrial: false,
    isOnetimeLesson: false,
    paymentAvailable: true,
    rate: 0,
    reviewCount: 0,
  },
];
